server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tour
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
tour:
  app:
    jwtSecret: ======================Tour=Management=Spring=Boot==========================
    jwtExpirationMs: 86400000