server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tour
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
tour:
  app:
    jwtSecret: ======================Tour=Management=Spring=Boot==========================
    jwtExpirationMs: 86400000